# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:5432/orders
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.hikari.connection-timeout=30000
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email (AWS SES via SMTP)
spring.mail.host=email-smtp.ap-southeast-2.amazonaws.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Web
server.forward-headers-strategy=framework
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/
springdoc.api-docs.servers[0].url=https://cupcakes-api.leighwest.dev

# AWS
spring.cloud.aws.region.static=ap-southeast-4
sqs.order-created-queue=order-created
sqs.order-dispatched-queue=order-dispatched

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never