server {
    listen 80;
    server_name cupcakes-api.leighwest.dev;

    # Redirect all HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cupcakes-api.leighwest.dev;

    ssl_certificate     /etc/letsencrypt/live/cupcakes-api.leighwest.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cupcakes-api.leighwest.dev/privkey.pem;

    location / {
        proxy_pass         http://orders:8080;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}